import fs from "node:fs";
import path from "node:path";
// Corrige le sélecteur de personas sur /offres (rendu dynamique => liste à jour).
const files = {
  "app/[locale]/offres/page.tsx": "aW1wb3J0IHsgU3VzcGVuc2UgfSBmcm9tICdyZWFjdCc7CmltcG9ydCB7IE9mZnJlc1BlcnNvbmFzIH0gZnJvbSAnQC9jb21wb25lbnRzL09mZnJlc1BlcnNvbmFzJzsKaW1wb3J0IHsgZ2V0UGVyc29uYXMsIHR5cGUgV3BMb2NhbGUgfSBmcm9tICdAL2xpYi93b3JkcHJlc3MnOwppbXBvcnQgdHlwZSB7IE1ldGFkYXRhIH0gZnJvbSAnbmV4dCc7CgpleHBvcnQgYXN5bmMgZnVuY3Rpb24gZ2VuZXJhdGVNZXRhZGF0YSh7IHBhcmFtczogeyBsb2NhbGUgfSB9OiB7IHBhcmFtczogeyBsb2NhbGU6IFdwTG9jYWxlIH0gfSk6IFByb21pc2U8TWV0YWRhdGE+IHsKICBjb25zdCBtID0gKGF3YWl0IGltcG9ydChgLi4vLi4vLi4vbWVzc2FnZXMvJHtsb2NhbGV9Lmpzb25gKSkuZGVmYXVsdC5tZXRhIGFzIFJlY29yZDxzdHJpbmcsIHN0cmluZz47CiAgcmV0dXJuIHsKICAgIHRpdGxlOiBtLm9mZnJlc1RpdGxlLAogICAgZGVzY3JpcHRpb246IG0ub2ZmcmVzRGVzYywKICAgIGFsdGVybmF0ZXM6IHsgY2Fub25pY2FsOiAnL29mZnJlcycsIGxhbmd1YWdlczogeyBmcjogJy9vZmZyZXMnLCBlbjogJy9lbi9vZmZyZXMnIH0gfSwKICB9Owp9CgpleHBvcnQgY29uc3QgZHluYW1pYyA9ICdmb3JjZS1keW5hbWljJzsKZXhwb3J0IGNvbnN0IGZldGNoQ2FjaGUgPSAnZm9yY2Utbm8tc3RvcmUnOwoKZXhwb3J0IGRlZmF1bHQgYXN5bmMgZnVuY3Rpb24gT2ZmcmVzUGFnZSh7IHBhcmFtczogeyBsb2NhbGUgfSB9OiB7IHBhcmFtczogeyBsb2NhbGU6IFdwTG9jYWxlIH0gfSkgewogIGNvbnN0IHBlcnNvbmFzID0gYXdhaXQgZ2V0UGVyc29uYXMobG9jYWxlKTsKICByZXR1cm4gKAogICAgPG1haW4+CiAgICAgIDxTdXNwZW5zZSBmYWxsYmFjaz17bnVsbH0+CiAgICAgICAgPE9mZnJlc1BlcnNvbmFzIHBlcnNvbmFzPXtwZXJzb25hc30gLz4KICAgICAgPC9TdXNwZW5zZT4KICAgIDwvbWFpbj4KICApOwp9Cg=="
};
for (const [f, b] of Object.entries(files)) {
  fs.mkdirSync(path.dirname(f), { recursive: true });
  fs.writeFileSync(f, Buffer.from(b, "base64").toString("utf8"));
  console.log("corrigé :", f);
}
console.log("\n✓ Fait. Ctrl+C puis : npm run dev (ou redéploie si Vercel)");
